import {
  Calendar,
  Users,
  Heart,
  Compass,
  ShieldCheck,
  TrendingUp,
  Lightbulb,
  MessageCircle,
  MessageCircleQuestion,
  BookOpen,
  Target,
  Laptop,
  Book,
  Pencil,
  Video,
  Download,
  Star,
  Sprout,
  Sigma,
  FlaskConical,
  Dna,
  Globe,
  Languages,
  Mic,
  Building2,
  Monitor,
  Shuffle,
  GraduationCap,
  Phone,
  Mail,
  Clock,
  MapPin,
  CheckCircle,
  ChevronDown,
  ChevronUp,
  Menu,
  X,
  ArrowRight,
  Quote,
  Smile,
  Facebook,
  Instagram,
  Linkedin,
  Twitter,
  Youtube,
  type LucideIcon,
  type LucideProps,
} from "lucide-react";

const registry: Record<string, LucideIcon> = {
  calendar: Calendar,
  users: Users,
  heart: Heart,
  compass: Compass,
  "shield-check": ShieldCheck,
  "trending-up": TrendingUp,
  lightbulb: Lightbulb,
  "message-circle": MessageCircle,
  "message-circle-question": MessageCircleQuestion,
  "book-open": BookOpen,
  target: Target,
  laptop: Laptop,
  book: Book,
  pencil: Pencil,
  video: Video,
  download: Download,
  star: Star,
  sprout: Sprout,
  sigma: Sigma,
  "flask-conical": FlaskConical,
  dna: Dna,
  globe: Globe,
  languages: Languages,
  mic: Mic,
  "building-2": Building2,
  monitor: Monitor,
  shuffle: Shuffle,
  "graduation-cap": GraduationCap,
  phone: Phone,
  mail: Mail,
  clock: Clock,
  "map-pin": MapPin,
  "check-circle": CheckCircle,
  "chevron-down": ChevronDown,
  "chevron-up": ChevronUp,
  menu: Menu,
  x: X,
  "arrow-right": ArrowRight,
  quote: Quote,
  smile: Smile,
  facebook: Facebook,
  instagram: Instagram,
  linkedin: Linkedin,
  twitter: Twitter,
  youtube: Youtube,
};

export type IconName = keyof typeof registry;

/**
 * Resolves an icon name (as stored in content/*.ts) to a lucide-react
 * component. Centralising this means content data can stay plain strings —
 * easy for a non-developer to edit — while the actual icon set used by the
 * site is swappable in this one file.
 */
export function Icon({ name, ...props }: { name: string } & LucideProps) {
  const Component = registry[name] ?? Star;
  return <Component {...props} />;
}
